### ISSUE TITLE
Internal Loadbalancer support

### ISSUE THREAD

**Issue by Daviey** [terraform-google-modules/terraform-google-vault#57]
The README.md states "You can alter the load balancer to be an internal-only load balancer if needed" (https://github.com/terraform-google-modules/terraform-google-vault/blob/master/README.md#faq).  However, there is no guidance on how this would be done.

Looking at the module, it appears to be hard-coded.  This implies that having an internal-only load balancer requires forking the module which is less than ideal

https://github.com/terraform-google-modules/terraform-google-vault/blob/9a8512f0badc55f8c5bb393e1e3dd8e8bf372631/servers.tf#L104

If I am mistaken, is it possible to include some guidance on how to achieve this or if it doesn't currently support this, can support for an Internal LB be added?  Thanks

**Comment by chanuka-techo** [comment]
I have done this in a private fork. Reserved an INTERNAL IP. Updated forwarding rule with that. changed `load_balancing_scheme` to INTERNAL. 

Created a `google_compute_region_backend_service` and added `google_compute_region_instance_group_manager` as a backend to it. Set that as `backend_service` for `google_compute_forwarding_rule` instead of `target_pool`.

Also created an http health-chek with `google_compute_health_check` .

Hope that helps.
