### ISSUE TITLE
Terraform Cloud Gotchas

### ISSUE THREAD

**Issue by guhcampos** [terraform-google-modules/terraform-google-vault#67]
Hi,

This is more of a documentation issue perhaps? 

I think it's useful to make a note this module does not work with Terraform Cloud, because it uses the `local_file` provider. Your run on TF Cloud will fail at the last very step, which consists of dowloading generated certificates to the local machine.

There is no work around, my suggestion would be to change the module to use a GCS bucket instead of a local file to save the resulting certificate. 

If you - like me - only found this out on the last minute, you can set the execution model of your Terraform Workspace to `local`, so you'll at least be able to keep using the shared state from the `remote` backend and not have to destroy everything.

**Comment by sethvargo** [comment]
Hi @guhcampos 

We call out the "localness" of this module in the README [at the end](https://github.com/terraform-google-modules/terraform-google-vault#local-security). I just pushed up 34dbd2f7a0803111e15b583c89642f51e2343357 which adds an option for not writing the CA locally.

However, because Terraform does not yet support encrypting data with KMS, I think it's still going to fail because of how our KMS encryption script works writing a cache into `.terraform`.
